OVERWRITE_PROJECT_ID = "Project_bebc4f75"

OVERWRITE_AVALON_DATA = [
    {
        "_id": "614ae8dfef6bfb71c7a5475a",
        "type": "project",
        "name": OVERWRITE_PROJECT_ID,
        "data": {
            "clipIn": 1,
            "clipOut": 1,
            "fps": 25.0,
            "frameEnd": 0,
            "frameStart": 0,
            "handleEnd": 0,
            "handleStart": 0,
            "pixelAspect": 0,
            "resolutionHeight": 0,
            "resolutionWidth": 0,
            "tools_env": [],
            "code": "",
            "library_project": False,
            "visualParent": None,
        },
        "schema": "openpype:project-3.0",
        "config": {"tasks": None},
        "parent": None,
    },
    {
        "_id": "614ae8dfef6bfb71c7a5475b",
        "type": "asset",
        "name": "Asset",
        "data": {
            "clipIn": 1,
            "clipOut": 1,
            "fps": 25.0,
            "frameEnd": 0,
            "frameStart": 0,
            "handleEnd": 0,
            "handleStart": 0,
            "pixelAspect": 0,
            "resolutionHeight": 0,
            "resolutionWidth": 0,
            "tools_env": [],
            "parent": [],
            "visualParent": None,
            "tasks": None,
            "parents": [],
        },
        "schema": "openpype:project-3.0",
        "parent": "614ae8dfef6bfb71c7a5475a",
    },
    {
        "_id": "614ae8dfef6bfb71c7a5475c",
        "type": "asset",
        "name": "PRP",
        "data": {
            "clipIn": 1,
            "clipOut": 1,
            "fps": 25.0,
            "frameEnd": 0,
            "frameStart": 0,
            "handleEnd": 0,
            "handleStart": 0,
            "pixelAspect": 0,
            "resolutionHeight": 0,
            "resolutionWidth": 0,
            "tools_env": [],
            "parent": [],
            "visualParent": "614ae8dfef6bfb71c7a5475b",
            "tasks": None,
            "parents": ["Asset"],
        },
        "schema": "openpype:project-3.0",
        "parent": "614ae8dfef6bfb71c7a5475a",
    },
    {
        "_id": "614ae8dfef6bfb71c7a5475d",
        "type": "asset",
        "name": "Fork",
        "data": {
            "clipIn": 1,
            "clipOut": 1,
            "fps": 25.0,
            "frameEnd": 0,
            "frameStart": 0,
            "handleEnd": 0,
            "handleStart": 0,
            "pixelAspect": 0,
            "resolutionHeight": 0,
            "resolutionWidth": 0,
            "tools_env": [],
            "parent": [],
            "visualParent": "614ae8dfef6bfb71c7a5475c",
            "tasks": None,
            "parents": ["Asset", "PRP"],
        },
        "schema": "openpype:project-3.0",
        "parent": "614ae8dfef6bfb71c7a5475a",
    },
]

OVERWRITE_SHOTGRID_DATA = [
    {
        "_id": OVERWRITE_PROJECT_ID,
        "src_id": 111,
        "type": "Project",
        "parent": None,
    }
]


OVERWRITE_INTERMEDIATE_DB_DATA = [
    {
        "_id": OVERWRITE_PROJECT_ID,
        "src_id": 111,
        "type": "Project",
        "parent": None,
        "object_id": "614ae8dfef6bfb71c7a5475a",
    },
    {
        "_id": "Asset",
        "type": "Group",
        "parent": ",Project_bebc4f75,",
        "object_id": "614ae8dfef6bfb71c7a5475b",
    },
    {
        "_id": "PRP",
        "type": "Group",
        "parent": ",Project_bebc4f75,Asset,",
        "object_id": "614ae8dfef6bfb71c7a5475c",
    },
    {
        "_id": "Fork",
        "src_id": 16284,
        "type": "Asset",
        "parent": ",Project_bebc4f75,Asset,PRP,",
        "object_id": "614ae8dfef6bfb71c7a5475d",
    },
]
