PROJECT_ID = "Project_564e3805"
AVALON_DATA = [
    {
        "_id": "614b3e4214dbac102817bb1b",
        "type": "project",
        "name": PROJECT_ID,
        "data": {
            "clipIn": 1,
            "clipOut": 1,
            "fps": 25.0,
            "frameEnd": 0,
            "frameStart": 0,
            "handleEnd": 0,
            "handleStart": 0,
            "pixelAspect": 0,
            "resolutionHeight": 0,
            "resolutionWidth": 0,
            "tools_env": [],
            "code": "",
            "library_project": False,
            "visualParent": None,
        },
        "schema": "openpype:project-3.0",
        "config": {"tasks": None},
        "parent": None,
    },
    {
        "_id": "614b3e4214dbac102817bb1c",
        "type": "asset",
        "name": "Asset",
        "data": {
            "clipIn": 1,
            "clipOut": 1,
            "fps": 25.0,
            "frameEnd": 0,
            "frameStart": 0,
            "handleEnd": 0,
            "handleStart": 0,
            "pixelAspect": 0,
            "resolutionHeight": 0,
            "resolutionWidth": 0,
            "tools_env": [],
            "parent": [],
            "visualParent": None,
            "tasks": None,
            "parents": [],
        },
        "schema": "openpype:project-3.0",
        "parent": "614b3e4214dbac102817bb1b",
    },
    {
        "_id": "614b3e4214dbac102817bb1d",
        "type": "asset",
        "name": "PRP",
        "data": {
            "clipIn": 1,
            "clipOut": 1,
            "fps": 25.0,
            "frameEnd": 0,
            "frameStart": 0,
            "handleEnd": 0,
            "handleStart": 0,
            "pixelAspect": 0,
            "resolutionHeight": 0,
            "resolutionWidth": 0,
            "tools_env": [],
            "parent": [],
            "visualParent": "614b3e4214dbac102817bb1c",
            "tasks": None,
            "parents": ["Asset"],
        },
        "schema": "openpype:project-3.0",
        "parent": "614b3e4214dbac102817bb1b",
    },
    {
        "_id": "614b3e4214dbac102817bb1e",
        "type": "asset",
        "name": "Fork",
        "data": {
            "clipIn": 1,
            "clipOut": 1,
            "fps": 25.0,
            "frameEnd": 0,
            "frameStart": 0,
            "handleEnd": 0,
            "handleStart": 0,
            "pixelAspect": 0,
            "resolutionHeight": 0,
            "resolutionWidth": 0,
            "tools_env": [],
            "parent": [],
            "visualParent": "614b3e4214dbac102817bb1d",
            "tasks": None,
            "parents": ["Asset", "PRP"],
        },
        "schema": "openpype:project-3.0",
        "parent": "614b3e4214dbac102817bb1b",
    },
]
SHOTGRID_DATA = [
    {
        "_id": PROJECT_ID,
        "src_id": 111,
        "type": "Project",
        "parent": None,
    },
    {"_id": "Asset", "type": "Group", "parent": ",Project_564e3805,"},
    {"_id": "PRP", "type": "Group", "parent": ",Project_564e3805,Asset,"},
    {
        "_id": "Knife",
        "src_id": 23549,
        "type": "Asset",
        "parent": ",Project_564e3805,Asset,PRP,",
    },
]
INTERMEDIATE_DB_DATA = [
    {
        "_id": PROJECT_ID,
        "src_id": 111,
        "type": "Project",
        "parent": None,
        "object_id": "614b3e4214dbac102817bb1b",
    },
    {
        "_id": "Asset",
        "type": "Group",
        "parent": ",Project_564e3805,",
        "object_id": "614b3e4214dbac102817bb1c",
    },
    {
        "_id": "PRP",
        "type": "Group",
        "parent": ",Project_564e3805,Asset,",
        "object_id": "614b3e4214dbac102817bb1d",
    },
    {
        "_id": "Fork",
        "src_id": 23549,
        "type": "Asset",
        "parent": ",Project_564e3805,Asset,PRP,",
        "object_id": "614b3e4214dbac102817bb1e",
    },
]
